def main():
	f = open('big.txt', 'r')
	w = open('cleaned_big.txt','w')
	content = f.readlines()
	for i in range(0, len(content)):
		s = content[i]
		s = s.lower()
		s = s.replace(".", "")
		s = s.replace("\'", "")
		s = s.replace(",", "")
		s = s.replace("\"", "")
		s = s.replace(";", "")
		s = s.replace("*", "")
		s = s.replace(")", "")	
		s = s.replace("(", "")
		s = s.replace(":", "")
		s = s.replace("[", "")	
		s = s.replace("]", "")
		s = s.replace("?", "")	
		s = s.replace("!", "")
		s = s.replace("-", "")
		s = s.replace("_", "")
		s = s.replace("^", "")
		s = s.replace("&", "")
		s = s.replace("@", "")
		s = s.replace("#", "")
		s = s.replace("$", "")
		s = s.replace("%", "")
		s = s.replace(">", "")	
		s = s.replace("<", "")	
		s = s.replace("|", "")
		s = s.replace("+", "")	
		s = s.replace("=", "")											
		w.write(s)
main()